[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.17"

[features]
resolution = true
skip-lint = false

[programs.localnet]
wormhole_guardian_adapter = "74nfEtQSch83m7hk6odpHGxis6R4Vyu56ZWxwBoCXtdD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[test.validator]
# Deactivate the "bpf_account_data_direct_mapping" feature for testing
deactivate_feature = ["EenyoWx9UMXYKpR8mW5Jmfmy2fRjzUtM7NduYMY8bx33"]

[[test.genesis]]
address = "FMPF1RnXz1vvZ6eovoEQqMPXYRUgYqFKFMXzTJkbWWVD"
program = "tests/artifacts/endpoint.so"

[[test.genesis]]
address = "661Ly6gSCDiGWzC4tKJhS8tqXNWJU6yfbhxNKC4gPF5t"
program = "tests/artifacts/mock_integrator.so"

[[test.genesis]]
address = "EtZMZM22ViKMo4r5y4Anovs3wKQ2owUmDpjygnMMcdEX"
program = "tests/artifacts/wormhole_post_message_shim.so"

[[test.genesis]]
address = "EFaNWErqAtVWufdNb7yofSHHfWFos843DFpu4JBw24at"
program = "tests/artifacts/wormhole_verify_vaa_shim.so"

## CORE BRIDGE MAINNET (Solana mainnet)
### Wormhole Core Bridge Program (Mainnet)
[[test.genesis]]
address = "worm2ZoG2kUd4vFXhvjh93UUH596ayRfgQ2MgjNMTth"
program = "tests/artifacts/mainnet_core_bridge.so"

### Wormhole Core Bridge (Mainnet) -- Config
[[test.validator.account]]
address = "2yVjuQwpsvdsrywzsJJVs9Ueh4zayyo5DYJbBNc3DDpn"
filename = "tests/accounts/mainnet/core_bridge_config.json"

### Wormhole Core Bridge (Mainnet) -- Fee Collector
[[test.validator.account]]
address = "9bFNrXNb2WTx8fMHXCheaZqkLZ3YCCaiqTftHxeintHy"
filename = "tests/accounts/mainnet/core_bridge_fee_collector.json"

### Wormhole Core Bridge (Mainnet) -- Guardian Set 0 (but with devnet guardian)
[[test.validator.account]]
address = "DS7qfSAgYsonPpKoAjcGhX9VFjXdGkiHjEDkTidf8H2P"
filename = "tests/accounts/mainnet/guardian_set_0.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/wormhole-guardian-adapter.ts"
