[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.17"

[features]
resolution = true
skip-lint = false

[programs.localnet]
wormhole_guardian_adapter = "gWFRjvvXvUnNy64MsywLjXbKoWg1pb4DMLbRZnHuE1m"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[[test.genesis]]
address = "FMPF1RnXz1vvZ6eovoEQqMPXYRUgYqFKFMXzTJkbWWVD"
program = "lib/example-messaging-endpoint/svm/target/deploy/endpoint.so"

[[test.genesis]]
address = "661Ly6gSCDiGWzC4tKJhS8tqXNWJU6yfbhxNKC4gPF5t"
program = "lib/example-messaging-endpoint/svm/target/deploy/mock_integrator.so"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/svm.ts"
