[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.17"

[features]
resolution = true
skip-lint = false

[programs.localnet]
wormhole_guardian_adapter = "gWFRjvvXvUnNy64MsywLjXbKoWg1pb4DMLbRZnHuE1m"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[[test.genesis]]
address = "FMPF1RnXz1vvZ6eovoEQqMPXYRUgYqFKFMXzTJkbWWVD"
program = "lib/example-messaging-endpoint/svm/target/deploy/endpoint.so"

[[test.genesis]]
address = "661Ly6gSCDiGWzC4tKJhS8tqXNWJU6yfbhxNKC4gPF5t"
program = "lib/example-messaging-endpoint/svm/target/deploy/mock_integrator.so"

## CORE BRIDGE TESTNET (Solana devnet)
### Wormhole Core Bridge Program (Testnet)
# [[test.validator.clone]]
# address = "3u8hJUVTA4jH1wYAyUur7FFZVQ8H635K3tSHHF4ssjQ5"
[[test.genesis]]
address = "3u8hJUVTA4jH1wYAyUur7FFZVQ8H635K3tSHHF4ssjQ5"
program = "tests/artifacts/testnet_core_bridge.so"

### Wormhole Core Bridge (Testnet) -- Config
[[test.validator.account]]
address = "6bi4JGDoRwUs9TYBuvoA7dUVyikTJDrJsJU1ew6KVLiu"
filename = "tests/accounts/core_bridge_testnet/config.json"

### Wormhole Core Bridge (Testnet) -- Guardian Set 0
[[test.validator.account]]
address = "dxZtypiKT5D9LYzdPxjvSZER9MgYfeRVU5qpMTMTRs4"
filename = "tests/accounts/core_bridge_testnet/guardian_set_0_mock.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/svm.ts"
